### PR TITLE
Translations: update de

### PR DESCRIPTION
**Pull request by Narrat**
Noticed some issues with the `de` translation.
Should be in a better shape with the changes from the PR (but by no means perfect :D)

### CODE REVIEW

**Comment by Consolatis** [comment]
Small review from a native German speaker: All the proposed changes make sense.

There was some fun stuff in here before, like
> WARNUNG: Benutzt Dateien aus Openbox. Das wird nicht richtig werken.
> Fokussiert nächstes Spitzenniveau

**Comment by keithbowes** [comment]
Sorry about my mistakes.  I'd like to think that I'm proficient in German, but I've only been studying it for 30 years.

**Comment by keithbowes** [comment]
.
> > Fokussiert nächstes Spitzenniveau

What's wrong with that?  A bad translation of toplevel?  Interestingly, the Firefox spell-checker (Hunspell) gives me a red line under "toplevel" but not under "Spitzenniveau".  Actually, I'm guessing that that form was chosen because it wasn't marked as an error.  I do remember checking the GTK translations and they really didn't make sense; I'm not sure "höhere Ebene" really captures the meaning of "toplevel" (a toplevel is just a window that's not a popup).  Plus that message is only visible when you use --debug; it's just an informational message that a new toplevel has been focused, along with the app_id.

It was useful in the past, when I was trying to get focusing toplevels to work correctly, but I actually considered removing it during the migration to wlr_scene, but I left it there for some reason.  In older versions, "toplevels" were called "views", inherited from Weston, but when tinywl changed all instances of "view" to "toplevel" (to properly reflect Wayland terminology), so did I (long story, but I noticed that tinybox still uses the "view" terminology). I also considered keeping the terminology "view" in the translations, since "toplevel" is a bit confusing, implying that it's the window on the top and not just any window that's not a popup.

**Comment by Narrat** [comment]
I had some kind of tunnel vision when something caught my eye and didn't check if every translation is in use or not :D
And you don't need to be sorry about the mistakes. I've seen worse than that. And if interested I can add comments to the lines explaining the rationale behind the changes, which may help with further enhancing your understanding of the language.
I only deduced the meaning of a line from the translation file without looking at the code. So yeah, after your explanation I see why "höhere Ebene" isn't perfectly fitting. I thought more of it in a literal way. Need to look it up, but i may be possible that in a technical context toplevel/top-level got incorporated into the language as frame was. Or window could be described as "höchste Ebene" :D

Regarding `Spitzenniveau`: The word in and itself is correct and does exist. But it isn't used in that context, which makes the sentence kinda funny. `Spitzenniveau` is for example used on graphs/measurements if values exceed a certain expectation. Or if one product is compared with ones from competitors and beats them in whatever metric. Or companies use it to suggest they're are a leading factor in a certain area or in general. Like a clinic which exceeds at heart operations.

**Comment by Consolatis** [comment]
> I also considered keeping the terminology "view" in the translations, since "toplevel" is a bit confusing, implying that it's the window on the top and not just any window that's not a popup.

Personally I'd indeed go with `Fenster` (`window`) here. But I hardly ever configure anything to use German translations anyway (usually because of literal translations like this) so I might be biased in that regard.

**Comment by keithbowes** [comment]
> And if interested I can add comments to the lines explaining the rationale behind the changes, which may help with further enhancing your understanding of the language.

That's not necessary.  It's not like I'll ever be conversing in German (unless I go up to Amish country).  I mainly use it so that my family (parents and siblings) won't have any idea what I'm talking about and I don't have to use proper German for that.  It would be nice if my translations were correct, but I only do it in projects I write; for software that already have a German translation, I just let fluent speakers do their thing.

After I quit going to college and my depression wasn't going away, my parents made me go to a psychiatrist, who said that I might have a schizoid personality.  However, looking it up online, one of the traits is indifference to praise or criticism, which is definitely not me; it takes ages for me to get the courage to read my messages because I really hate being criticized (I know, I should be used to it by now), hence why I haven't responded in two weeks.  I suppose I'll merge it, since nothing I said led to any changes.

**Pull request merged**
